### ISSUE TITLE
Tagesordnung für ViKo 2024-08-21

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#43]
@simonkriegnerschramml - ich habe hier die TO-Punkt für morgen gesammelt, damit wir nichts vergessen. Gerne ergänzen, sollte ich was übersehen haben:

- [x] Stammdaten, aktueller Stand ( betrifft, #17 , #39 )
  - Aktueller Stand passt soweit , bis auf nächsten Punkt
- [x] Immer noch Frage zu  ID 1.1.2860 und anderen Sonderkulturen (kein Bereich unter X Tonnen)
  - Simon arbeitet da nach drüber
- [x] Feld Ackerzahl, endgültige Festlegung ( siehe https://github.com/w3geo/bml-fast/issues/40#issuecomment-2298095509 )
  - Wird durch Select mit < 30 und >= 30 ersetzt
- [x] Nmin Eingabe zur Aussaat von Gemüsekulturen ( #41 )
   - Wird von Simon noch detailliert, im Prinzip: Immer wenn Gemüsekultur, muss auch NMin Wert erfasst werden, entweder berechnet oder wahlweise manuell (eigene Messung). Auch bei Vorfrucht! 
- [x] Handelsdünger ( https://github.com/w3geo/bml-fast/issues/17#issuecomment-2296336988 )
- [x] Default-Schlagnummer sinnvoll (aus Inspire URL)?
  - Eher mäßig sinnvoll, weil Nummer vom Vorjahr
- [x] Nährstoffbilanz - Darstellung auf Basis aktueller Eingaben
   - Zu Beginn für das Testen sehr ausführlich, am Ende Streamlining auf eine Live-Tabelle, Berechnung muss verständlich sein.
- [x] Düngeobergrenzen der Kulturen darstellen - Wie kann das erfolgen? Sinnhafte Überlegungen.
  - In Live-Tabelle, Simon wird Beispiel bereitstellen, wie es für den User aussehen kann (Best Practice aus anderen Programmen, Tabellen-Darstellung mit 2 (?) Spalten. Intern zum Testen auch Zwischenschritte darstellen (Debugging-Ansicht).

**Comment by simonkriegnerschramml** [comment]
> @simonkriegnerschramml - ich habe hier die TO-Punkt für morgen gesammelt, damit wir nichts vergessen. Gerne ergänzen, sollte ich was übersehen haben:
> 
> * [ ]  Stammdaten, aktueller Stand ( betrifft, [Stammdaten (Issue für alle Stammdaten) #17](https://github.com/w3geo/bml-fast/issues/17) , [Problematik Bereichsangaben, Beispielfälle #39](https://github.com/w3geo/bml-fast/issues/39) )
> * [ ]  Feld Ackerzahl, endgültige Festlegung ( siehe [Fragen und Lösungen aus Videokonferenz 2024-08-19 #40 (comment)](https://github.com/w3geo/bml-fast/issues/40#issuecomment-2298095509) )
> * [ ]  Nmin Eingabe zur Aussaat von Gemüsekulturen ( [Nmin Eingabe zur Aussaat von Gemüsekulturen #41](https://github.com/w3geo/bml-fast/issues/41) )
> * [ ]  Handelsdünger ( [Stammdaten (Issue für alle Stammdaten) #17 (comment)](https://github.com/w3geo/bml-fast/issues/17#issuecomment-2296336988) )
> * [ ]  Default-Schlagnummer sinnvoll (aus Inspire URL)?

>* [ ] Nährstoffbilanz - Darstellung auf Basis aktueller Eingaben
>* [ ] Düngeobergrenzen der Kulturen darstellen - Wie kann das erfolgen? Sinnhafte Überlegungen.
>* [ ] Vorfruchtwert/Nmin Darstellung bei Gemüse - von Folgeaussaat Hauptfrucht abhängig.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

Zu folgendem Punkt möchte ich etwas ergänzen:

"Düngeobergrenzen der Kulturen darstellen - Wie kann das erfolgen? Sinnhafte Überlegungen.
In Live-Tabelle, Simon wird Beispiel bereitstellen, wie es für den User aussehen kann (Best Practice aus anderen Programmen, Tabellen-Darstellung mit 2 (?) Spalten. Intern zum Testen auch Zwischenschritte darstellen (Debugging-Ansicht)."

Leider kann ich aus unserem aktuellen Aufzeichnungsprogramm kein Beispiel für eine Nährstoffbilanz auftreiben, da unseren Anforderungen entsprechen würde. Wir haben das immer je Kultur dargestellt und Beginnen ab einer weiteren Hauptfrucht immer wieder von vorne.

Ich schicke dir einmal einen Screenshot, damit du dir vorstellen kannst, was ich hier genau meine.
![Nährstoffbilanz - ÖDüPlan Plus](https://github.com/user-attachments/assets/a3b0422d-382f-4d78-9006-ecbee49c3b9b)

Eine globale Darstellung gab es leider nur in unserem Vorgängerprogramm, welches aber mit 31.12.2023 vom Server genommen wurde. Auf dieses existiert leider kein Zugriff mehr.

LG
Simonm

**Comment by arnold-pichler** [comment]
Ich schließe das hier (letzter Kommentar wird in neues Issue übernommen)
